T1_GERAL_CASAS/Models/ErrorViewModel.cs
namespace T1_GERAL_CASAS.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

T1_GERAL_CASAS/Models/Libro.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.Contracts;

namespace T1_GERAL_CASAS.Models
{
    public class Libro
    {
        [Key]
        public int Id { get; set; }


        [Required(ErrorMessage = "El Titulo es obligatorio")]
        public string Titulo { get; set; }

        [Required(ErrorMessage = "El Autor es obligatorio")]
        public string Autor { get; set; }

        [Required(ErrorMessage = "El Tema es obligatorio")]
        public string Tema { get; set; }

        [Required(ErrorMessage = "La Editorial es obligatoria")]
        public string Editorial { get; set; }

        [Required(ErrorMessage = "El Año de publicacion es obligatorio")]
        [Range(1900, 3000, ErrorMessage = "El año de publicacion debe estar entre 1900 a 3000")]
        public int AnioPublicacion { get; set; }

        [Required(ErrorMessage = "El numero de paginas es obligatorio")]
        [Range(100, 1000, ErrorMessage = "El numero de paginas debe estar entre 100 a 1000")]
        public int Paginas { get; set; }


        [Required(ErrorMessage = "El numero de copias es obligatorio")]
        [Range(1, 20, ErrorMessage = "El numero de copias debe estar entre 1 a 20")]
        public int Copias { get; set; }


        [Required(ErrorMessage = "La descripcion es obligatoria")]
        public string Descripcion { get; set; }


        [Required(ErrorMessage = "La Categoria es obligatoria")]
        public string Categoria { get; set; }

        [Required(ErrorMessage = "El Material es obligatoria")]
        public string Material { get; set; }    
          

    }
}

T1_GERAL_CASAS/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using T1_GERAL_CASAS.Models;

namespace T1_GERAL_CASAS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

T1_GERAL_CASAS/Controllers/LibroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using T1_GERAL_CASAS.Datos;
using T1_GERAL_CASAS.Models;

namespace T1_GERAL_CASAS.Controllers
{
    public class LibroesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LibroesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Libroes
        public async Task<IActionResult> Index()
        {
              return _context.Libros != null ? 
                          View(await _context.Libros.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Libros'  is null.");
        }

        // GET: Libroes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Libros == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // GET: Libroes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Libroes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Autor,Tema,Editorial,AnioPublicacion,Paginas,Copias,Descripcion,Categoria,Material")] Libro libro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(libro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(libro);
        }

        // GET: Libroes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Libros == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros.FindAsync(id);
            if (libro == null)
            {
                return NotFound();
            }
            return View(libro);
        }

        // POST: Libroes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Autor,Tema,Editorial,AnioPublicacion,Paginas,Copias,Descripcion,Categoria,Material")] Libro libro)
        {
            if (id != libro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(libro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LibroExists(libro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(libro);
        }

        // GET: Libroes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Libros == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // POST: Libroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Libros == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Libros'  is null.");
            }
            var libro = await _context.Libros.FindAsync(id);
            if (libro != null)
            {
                _context.Libros.Remove(libro);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LibroExists(int id)
        {
          return (_context.Libros?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public IActionResult Disenio()
        {
            return View();
        }
        public IActionResult Arquitectura()
        {
            return View();
        }
    }
}

T1_GERAL_CASAS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">GRACIAS!</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

T1_GERAL_CASAS/Views/Libroes/Arquitectura.cshtml
@{
    ViewData["Title"] = "Arquitectura";
}

<h1>Arquitectura</h1>

<div class="tab-content mt-3" id="librosTabsContent">
    <!-- Pestaña Arquitectura -->
        <h3>Arquitectura de software las partes dificiles</h3>
        <div class="row">
            <div class="col-md-4">
                <img src="https://images.cdn3.buscalibre.com/fit-in/360x360/92/1d/921d0ddc0329a892b9bd2822e7f2503c.jpg" class="img-fluid" alt="Clean Architecture" />
                <p><strong>Arquitectura de Software: Las Partes Difíciles</strong> - Neil Ford, Patrick Kua, and Rebecca Parsons</p>
                <p>Este libro explora los aspectos más complejos de la arquitectura de software, tales como las decisiones difíciles que
                    los arquitectos deben tomar en entornos de alto cambio. Ofrece estrategias prácticas y ejemplos reales para manejar la
                    incertidumbre y construir soluciones que sean sostenibles a largo plazo.</p>
                <iframe width="100%" height="200" src="https://www.youtube.com/embed/iBPQ_bfSKWA?si=h0S367Anw3tNq8Qy" frameborder="0" allowfullscreen></iframe>
            </div>
            <!-- Puedes agregar más libros aquí -->
        </div>


    <h3>The Software Architect Elevator</h3>
    <div class="row">
    <div class="col-md-4">
            <img src="https://images.cdn1.buscalibre.com/fit-in/360x360/1b/e7/1be74e2398ab083835d3aaec567411bb.jpg" class="img-fluid" alt="The Software Architect Elevator" />
        <p><strong>The Software Architect Elevator</strong> - Gregor Hohpe</p>
        <p>En "The Software Architect Elevator", Gregor Hohpe explora cómo los arquitectos de software deben trasladarse entre los niveles operativos y estratégicos de una organización. El libro ofrece consejos prácticos sobre cómo navegar entre estos niveles para influir en el diseño y desarrollo del software, mientras se mantiene alineado con las necesidades empresariales.</p>
            <iframe width="100%" height="200" src="https://www.youtube.com/embed/7ZeCfN0eInQ?si=0Bl8tlt7MIe6spfX" frameborder="0" allowfullscreen></iframe>
    </div>
    </div>

T1_GERAL_CASAS/Views/Libroes/Create.cshtml
@model T1_GERAL_CASAS.Models.Libro

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tema" class="control-label"></label>
                <input asp-for="Tema" class="form-control" />
                <span asp-validation-for="Tema" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Editorial" class="control-label"></label>
                <input asp-for="Editorial" class="form-control" />
                <span asp-validation-for="Editorial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnioPublicacion" class="control-label"></label>
                <input asp-for="AnioPublicacion" class="form-control" />
                <span asp-validation-for="AnioPublicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Paginas" class="control-label"></label>
                <input asp-for="Paginas" class="form-control" />
                <span asp-validation-for="Paginas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Copias" class="control-label"></label>
                <input asp-for="Copias" class="form-control" />
                <span asp-validation-for="Copias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoria" class="control-label"></label>
                <input asp-for="Categoria" class="form-control" />
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Material" class="control-label"></label>
                <input asp-for="Material" class="form-control" />
                <span asp-validation-for="Material" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

T1_GERAL_CASAS/Views/Libroes/Delete.cshtml
@model T1_GERAL_CASAS.Models.Libro

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tema)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tema)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Editorial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Editorial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnioPublicacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnioPublicacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paginas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paginas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Copias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Copias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Material)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Material)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

T1_GERAL_CASAS/Views/Libroes/Details.cshtml
@model T1_GERAL_CASAS.Models.Libro

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tema)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tema)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Editorial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Editorial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnioPublicacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnioPublicacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paginas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paginas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Copias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Copias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Material)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Material)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

T1_GERAL_CASAS/Views/Libroes/Disenio.cshtml
@{
    ViewData["Title"] = "Disenio";
}

<h1>Diseño</h1>

    <!-- Pestaña Diseño -->
<h3>
    Clean Architecture: A Craftsman's Guide to Software Structure and Design
</h3>
        <div class="row">
            <div class="col-md-4">
        <img src="https://images.cdn2.buscalibre.com/fit-in/360x360/71/8a/718a4cccdea44cf4b37c74a93f5bf96d.jpg" class="img-fluid"/>
        <p><strong>Clean Architecture</strong> - Robert C. Martin</p>
        <p>En "Clean Architecture", Robert C. Martin presenta principios fundamentales para diseñar software flexible, escalable y fácil de mantener. Explora la importancia de separar las preocupaciones y las diferentes capas de una aplicación para permitir un desarrollo más ágil y limpio.</p>
        <iframe width="100%" height="200" src="https://www.youtube.com/embed/1OLSE6tX71Y?si=S1BsO3OoQpURGm8z" frameborder="0" allowfullscreen></iframe>
            </div>
            <!-- Agrega más libros aquí -->
        </div>

<h3>Refactoring: Improving the Design of Existing Code</h3>
<div class="row">
    <div class="col-md-4">
        <img src="https://m.media-amazon.com/images/I/71TGolfP8fL.jpg" class="img-fluid" alt="Design Patterns" />
        <p><strong>Refactoring: Improving the Design of Existing Code</strong>
        <p>Este libro es una guía clave para mejorar el diseño del código existente sin cambiar su funcionalidad. Aprenderás cómo realizar cambios progresivos y seguros en el código con el objetivo de mejorar su calidad y legibilidad.</p>
        <iframe width="100%" height="200" src="https://www.youtube.com/embed/CjCJ76oZXTE?si=EArhlJIL2zP-Oume" frameborder="0" allowfullscreen></iframe>
    </div>
    <!-- Agrega más libros aquí -->
</div>

T1_GERAL_CASAS/Views/Libroes/Edit.cshtml
@model T1_GERAL_CASAS.Models.Libro

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tema" class="control-label"></label>
                <input asp-for="Tema" class="form-control" />
                <span asp-validation-for="Tema" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Editorial" class="control-label"></label>
                <input asp-for="Editorial" class="form-control" />
                <span asp-validation-for="Editorial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnioPublicacion" class="control-label"></label>
                <input asp-for="AnioPublicacion" class="form-control" />
                <span asp-validation-for="AnioPublicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Paginas" class="control-label"></label>
                <input asp-for="Paginas" class="form-control" />
                <span asp-validation-for="Paginas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Copias" class="control-label"></label>
                <input asp-for="Copias" class="form-control" />
                <span asp-validation-for="Copias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoria" class="control-label"></label>
                <input asp-for="Categoria" class="form-control" />
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Material" class="control-label"></label>
                <input asp-for="Material" class="form-control" />
                <span asp-validation-for="Material" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

T1_GERAL_CASAS/Views/Libroes/Index.cshtml
@model IEnumerable<T1_GERAL_CASAS.Models.Libro>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tema)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Editorial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AnioPublicacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Paginas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Copias)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Material)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tema)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Editorial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnioPublicacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Paginas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Copias)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Material)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

T1_GERAL_CASAS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - T1_GERAL_CASAS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/T1_GERAL_CASAS.styles.css" asp-append-version="true" />
</head>
<body style="background-color: aliceblue; font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;" >
    <header style=>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3" style="background-color:aqua">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBC6wlFCGBpAPgPDRZ1CRu6L8Xw_q-dbXHrg&s" alt="Logo" style="height: 40px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Libroes" asp-action="Index">Libros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Libroes" asp-action="Disenio">Diseño</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Libroes" asp-action="Arquitectura">Arquitectura</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - T1_GERAL_CASAS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>